export const TRAER_PUBLICACIONES = 'TRAER_PUBLICACIONES'
export const TRAER_PUBLICACION_POR_USUARIO = 'TRAER_PUBLICACION_POR_USUARIO'
export const LOADING = 'LOADING_PUBLICACIONES';
export const ERROR = 'ERROR';