
export const ACTUALIZAR = 'PUBLICACIONES_ACTUALIZAR'
export const LOADING = 'LOADING_PUBLICACIONES';
export const ERROR = 'ERROR';
export const COM_LOADING = 'COM_LOADING';
export const COM_ERROR = 'COM_ERROR';
export const COM_ACTUALIZAR = 'COM_ACTUALIZAR'